# C++標準ライブラリ(コンテナ・イテレータ・汎用アルゴリズム)


## キーポイント

* コンテナは、複数のデータを利用しやすい形式で格納するクラス
* `vector`や`string`もコンテナの一種
* イテレータは、コンテナ内のデータの位置を示すクラスで、ポインタと似ている
* イテレータは、コンテナの種類が違っても同じように使えるが、添え字は一部のコンテナでしか使えない
* 汎用アルゴリズムは、イテレータを介してコンテナを操作する関数で、さまざまな種類がある
* 無名関数(ラムダ式)を使うと、汎用ライブラリの判定条件を自由に作成できる


----

## 1 コンテナ

----


### 1.1 C++標準ライブラリについて(再掲)

>**【注意事項】**<br>
>本テキストの内容はC++20バージョンを前提にしています。<br>
>古いバージョンのC++では、一部の機能が使えない場合があります。

C++標準ライブラリは、プログラミングにおける一般的な問題を解決するためによく使われる機能を、型(クラス)や関数、変数として定義し、それらをまとめたものです。

C++標準ライブラリには、以下の機能が含まれます。

* **C言語互換ライブラリ:**
    * **文字列と文字の操作：** 文字の操作と入出力を行う(`string`や`cin`、`cout`などを含む)
    * **数値計算などの数学関数：** べき乗、平方根、複素数、乱数など
    * **日付・時間：** 日時の取得、変換
* **ファイル操作:** ファイルを作成したり読み書きする
* **乱数:** 乱数の生成
* **汎用アルゴリズム：** イテレータを介してコンテナを操作する
* **コンテナ：** 複数のデータを利用しやすい形式で格納する
* **イテレータ：** コンテナや配列の中にある「データの位置」を示す
* **C++の言語能力を拡張するための機能：** スマートポインタ、デバッグ支援、数値型の制限情報、例外処理など

ライブラリの機能は膨大で、すべてを解説するにはとても長い時間がかかります。<br>
そこで、ライブラリの特に重要な部分に焦点を当て、２回に分けて解説することにします。

本テキストでは、次の機能を解説します。

1. コンテナ
2. イテレータ
3. 汎用アルゴリズム


#### C++の言語能力を拡張するための機能について

標準ライブラリには、C++に最初から組み込まれている機能だけでは実現できない、より複雑な機能を実現するためのクラスや関数が含まれます。これらの機能については、別の回に解説する予定です。


| ライブラリ名 | 概要 |
|:-------------|:-----|
| memory(メモリ) | 安全な動的メモリ管理 |
| thread(スレッド)<br>mutex(ミューテックス)<br>future(フューチャー) | マルチスレッド、並行プログラミングのサポート |
| exception(エクセプション) | 実行時エラーを補足・制御する「例外」機能のサポート |
| local(ロケール) | 多言語の情報の取得 |
| typeinfo(タイプ・インフォ) | 型の情報の取得 |


### 1.2 コンテナの概要

コンテナは「複数のデータを、利用しやすい形式で格納する型」です。<br>
実は、これまでに解説した`vector`型や`string`型もコンテナです。

次の表は、標準ライブラリに用意されている主要なコンテナです(コンテナは他にもあります)。

| コンテナ名 | 機能 | 特徴 |
|:-----------|:-----|:-----|
| <font size=3>vector</font>(ベクター) | <font size=3>配列</font> | データを連続的に、順序を保ったまま格納する |
| <font size=3>string</font>(ストリング) | <font size=3>文字列</font> | 文字の配列を文字列として扱う |
| <font size=3>unordered_map</font><br>(アンオーダード・マップ) | <font size=3>連想配列</font> | データを検索しやすいように並べ替えて格納する |
| <font size=3>list</font>(リスト) | <font size=3>連結リスト</font> | どの位置にデータを追加・削除する場合でも高速に実行できる |
| <font size=3>deque</font>(デック) | <font size=3>両端キュー</font> | データの追加や削除を、配列の末尾だけでなく先頭にも高速に実行できる |

これらのコンテナは、以下の3つの機能を持ちます。

* 格納されたデータを読み書きする機能
* データを処理するためのメンバ関数
* データを記録するためのメモリ領域の管理


### 1.3 格納されたデータを読み書きする機能

コンテナは、コンテナに格納されたデータを読み書きする機能を持っています。例えば`vector`や`string`の場合、`[]`演算子と添え字を使うことで読み書きできます。添字が使えないのコンテナの場合は、それぞれが専用の機能を持っています。

また、特定の位置のデータを簡単に読み書きする機能が用意されているコンテナもあります。例えば、`vector`や`string`には、先頭のデータを読み書きできる`front`(フロント)関数、末尾のデータを読み書きできる`back`(バック)関数が用意されています。

**コード**

```cpp
#include <iostream>
#include <vector>
using namespace std;

int main() {
  vector<int> v = { 1, 2, 3, 4, 5 };
  cout << v[2] << endl;      // 先頭から2番目のデータを読み取る
  cout << v.front() << endl; // 先頭のデータを読み取る
  cout << v.back() << endl;  // 末尾のデータを読み取る
}
```

**実行結果**

```txt
3
1
5
```


### 1.4 データを処理するためのメンバ関数

いくつかのコンテナには、格納されているデータを検索したり、データを置き換えたりするメンバ関数が用意されています。

例えば、`string`には、文字列を置換するための`replace`(リプレース)関数が用意されています。

**コード**

```cpp
#include <iostream>
#incluce <string>
using namespace std;

int main() {
  string s = "012345";
  // 2文字目から3つの文字をTwoThreeFourに置き換える
  s.replace(2, 3, "TwoThreeFour");
  cout << s << endl;
}
```

**実行結果**

```txt
01TwoThreeFour5
```


### 1.5 データを記録するためのメモリ領域の管理

`int`のような組み込み型の変数では、必要なメモリ、つまりメモ帳の行数は、整数ひとつを記録できる程度です(メモ帳の1行分くらい)。

しかし、`vector`や`string`のようなコンテナは、いくつでもデータを格納できます。さらに、格納しているデータを削除したり、新しく追加することもできます。メモ帳で例えると、いくつかのページをまとめてコンテナ用に予約しているようなものです。

データが追加されてメモするページが足りなくなったら、メモ帳の最後からページいくつかを抜き取って、コンテナ用のページの後ろに追加します(コンピューター上のメモ帳は、ページを外したり追加したりできるのです)。

なお、予約されているメモリ量は、`capacity`(キャパシティ)関数で調べられます。

**コード**

```cpp
#include <iostream>
#include <vector>
using namespace std;

int main() {
  vector<int> v = { 1, 2, 3 };
  cout << "push_back前のキャパシティ:" << v.capacity() << endl;
  v.push_back(4);
  cout << "push_back後のキャパシティ:" << v.capacity() << endl;
}
```

**実行結果**

```txt
push_back前のキャパシティ:3
push_back後のキャパシティ:6
```

----

## 2 イテレータ

----


### 2.1 イテレータの概要

イテレータは「ポインタの機能を要件ごとに分類して名前をつけたもの」で、日本語では「反復子(はんぷくし)」と呼ばれます。<br>
イテレータの目的は、さまざまなコンテナを共通の方法で処理できるようにすることです。

イテレータには複数の種類があり、種類ごとに機能要件が定められています。<br>
以下に、C++標準ライブラリで使われている基本的なイテレータの概要を示します。

| 種類 | 機能要件 | 対応するコンテナ |
|:-----|:-----|:---------------------|
| 入力イテレータ | データの読み取り、位置をひとつ進める、`==`と`!=`による比較ができる | cin, basic_istream |
| 出力イテレータ | データの書き込み、位置を一つ進めることができる(比較できる必要はない) | cout, basic_ostream |
| 前方向イテレータ | データの読み書き、イテレータ同士の比較、<br>位置をひとつ進めること(インクリメント)ができる | unordered_map |
| 双方向イテレータ | 前方向イテレータの機能に加えて、位置をひとつ戻すこと(デクリメント)ができる | list |
| ランダム・アクセス・イテレータ | 双方向イテレータの機能に加えて、位置を自由に変更(位置に整数を足し引き)すること、<br>2つのイテレータの距離を計算することができる | deque |
| 隣接イテレータ | ランダム・アクセス・イテレータの機能に加えて、<br>イテレータの指す要素が連続していることを保証する(ポインタと互換性がある) | vector, string |

イテレータの種類ごとの関係は、次の図のようになります。

$$
\boxed{
　　　隣接イテレータ(ポインタ) \\
\boxed{
　　ランダムアクセスイテレータ \\
\boxed {
\space 　　　　双方向イテレータ \\
\boxed {
　　　　前方向イテレータ\\
\boxed {
入力イテレータ
}
\boxed {
出力イテレータ
}}}}}
$$

例えば、「双方向イテレータ」は自分自身の機能に加えて、「前方向イテレータ」の機能も含みます。<br>
ですが、前方向イテレータは双方向アクセスイテレータの機能を持ちません。

C++標準ライブラリの関数は、受け付けるイテレータの種類が決まっています。

例えば、データを検索する`find`という関数は「入力イテレータ」を受け付けます。<br>
上位のイテレータは下位のイテレータを兼ねるので、「出力イテレータ」以外ならどのイテレータでも使えることに注意してください。

もうひとつの例として、データの並び順を逆にする`reverse`関数は、「双方向イテレータ」を受け付けます。<br>
効率的に並び順を逆にするには、「位置を一つ戻す」操作が必要になるからです。


### 2.2 コンテナからイテレータを得る方法

ほとんどのコンテナには、「保持しているデータを指すイテレータ」を取得する関数があります。

コンテナが保持する複数のデータに対して、データ範囲の先頭と終端の２種類のイテレータを取得できます。

* `begin`(ビギン)関数: データ範囲の先頭のイテレータを取得する。
* `end`(エンド)関数: データ範囲の終端のイテレータを取得する。

取得したイテレータを先頭から終端までインクリメントすることで、コンテナ全体を処理できます。<br>
以下は、イテレータを使ったfor文の例です。`vector<int>::iterator`は、`vector<int>`用のイテレータ型です。

**コード**

```cpp
#include <iostream>
#include <vector>
using namespace std;

int main() {
  vector<int> v = { 1, 4, 1, 4, 2, 1, 3, 5, 6 };

  for (vector<int>::iterator i = v.begin(); i != v.end(); i++) {
    cout << *i << ' ';
  }
  cout << endl;
}
```

**実行結果**

```txt
1 4 1 4 2 1 3 5 6
```

イテレータが指すデータを読み書きするには、ポインタと同様に`*`(アスタリスク)を使います。上のプログラムでは`*i`の部分でデータを読み出しています。


### 2.3 auto(オート)キーワード

イテレータ型には、長い名前のものが多いので、書くのが大変です。例えば`vector<int>`型用のイテレータの名前は、

`vector<int>::iterator`

なのでした。入力支援があったとしても、この長さの名前を何度も書きたい、という人は少ないと思います。

そこで、`auto`(オート)キーワードの出番です。`auto`キーワードの機能は「初期値から型を推測する」ことです。

**コード**

```cpp
#include <iostream>
#include <vector>
using namespace std;

int main() {
  vector<int> v = { 1, 4, 1, 4, 2, 1, 3, 5, 6 };

  for (auto i = v.begin(); i != v.end(); i++) {
    cout << *i << ' ';
  }
  cout << endl;
}
```

変数`i`は`v.begin()`の戻り値で初期化されています。<br>
`auto`キーワードは`v.begin()`の戻り値型をチェックして、変数`i`の型を`vector<int>::iterator`だと推測します。


----

## 3 汎用アルゴリズム

----


### 3.1 汎用アルゴリズムの概要

汎用アルゴリズムは「イテレータを介してコンテナを操作する関数」です。<br>
「テンプレート」という機能を利用して、コンテナの種類が違っても同じ関数が使えるように作られています。

汎用アルゴリズムを利用するには、`algorithm`(アルゴリズム)というヘッダをインクルードします。<br>
以下に、よく使われる汎用アルゴリズム関数の名前と機能を示します。

>2025年現在、C++には100種類以上の汎用アルゴリズムが定義されています。

| 関数名 | 概要 |
|:-------|:-----|
| <font size=3>find_if</font>(ファインド) | 範囲内から指定された条件を満たすデータを見つける |
| <font size=3>count</font>(カウント) | 範囲内にある指定されたデータの個数を数える |
| <font size=3>sort</font>(ソート) | 範囲内のデータを昇順に並べ替える |
| <font size=3>lower_bound</font>(ローワー・バウンド) | ソート済み範囲を効率的に検索する |
| <font size=3>reverse</font>(リバース) | 範囲内のデータの並び順を逆にする |
| <font size=3>replace</font>(リプレイス) | 範囲内の指定されたデータを別のデータで上書きする |
| <font size=3>remove_if</font>(リムーブ・イフ) | 範囲内の指定されたデータを削除する |
| <font size=3>equal</font>(イコール) | 2つの範囲の要素が等しいか判定する |
| <font size=3>unique</font>(ユニーク) | 隣り合う同じデータをひとつにまとめる |
| <font size=3>accumulate</font>(アキュムレート) | 範囲内のデータを合計する |
| <font size=3>swap</font>(スワップ) | 2つの変数の内容を入れ替える |
| <font size=3>min</font>(ミン) | 2つの変数のうち小さいほうを返す |
| <font size=3>max</font>(マックス) | 2つの変数のうち大きいほうを返す |

多くの汎用アルゴリズムは、操作する範囲の「先頭」と「終端」を示す2つのイテレータを引数として受け取ります。<br>
アルゴリズムによっては、追加の引数がある場合もあります。


### 3.2 オーバーロードとテンプレート

テンプレートは、

&emsp;**さまざまな異なる型に対して、共通して利用できる関数や構造体を定義する**

という機能です。汎用アルゴリズムは、「テンプレート」という機能を利用して作られています。

これまで、変数や関数、構造体を書くときには、いつも「型」を指定していました。<br>
例えば、「`vector<int>`配列の中身を合計した値を返す」関数は次のように書けます。

```cpp
int add(const vector<int>& v) {
  int n = 0;
  for (auto i = v.begin(); i != v.end(); i++) { n += *i; }
  return n;
}
```

当然ながら、この`add`関数は`vector<int>`型しか扱えません。<br>
もし`vector<double>`型も計算できるようにしたければ、`vector<double>`用の`add`関数の定義を追加します。

```cpp
double add(const vector<double>& v) {
  double n = 0;
  for (auto i = v.begin(); i != v.end(); i++) { n += *i; }
  return n;
}
```

このような、「関数名が同じで、引数の型や数が違う関数を定義する」ことを「オーバーロード」といいます。<br>
引数の型または数が違ってさえいれば、いくらでも関数をオーバーロードできます。

しかし、改めて2つの`add`関数の定義を見てみると、引数と変数の型が違うだけで、それ以外はほとんど同じプログラムです。<br>
同じプログラムを何度も書くのは面倒なうえ、なにか処理を変更したくなったら、全ての関数について正しく変更しなくてはなりません。

このように、型が違うだけで内容は同じ関数が必要な場合、「テンプレート」という機能を使います。テンプレートは、

**さまざまな異なる型に対して、共通して利用できる関数や構造体を定義する**

という機能です。テンプレート機能を使うと、2つの`add`関数の定義を、次のひとつの定義にまとめられます。

```cpp
template<typename T>
T add(const vector<T>& v) {
  T n = 0;
  for (auto i = v.begin(); i != v.end(); i++) { n += *i; }
  return n;
}
```

* `template`(テンプレート)キーワード:<br>
  関数をテンプレートとして定義するには、`template`キーワードを使います。<br>
  `template`キーワードの直後に、`<`と`>`で囲って1つ以上のテンプレート引数を宣言します。
* `typename`(タイプネーム)キーワード:<br>
  テンプレート引数を宣言するには、`typename`という「仮の型」を宣言するキーワードを使います。<br>
  `typename`キーワードに続けて「仮の型」の名前を書くと、その名前は通常の型のように使えるようになります。<br>
  `add`関数テンプレートの場合、「仮の型」の名前は`T`(ティー)です。

このように、テンプレートを使って定義された関数のことを、「関数テンプレート」といいます。

>「仮の型」の名前のルールは変数や構造体と同じで、「1文字目は英字、2文字目以降は英数字または`_`記号」です。



### 3.3 swap(スワップ)関数

C++の標準ライブラリには、C言語から引き継いだライブラリと、C++で追加されたライブラリの両方が含まれます。<br>
このうち、「C++で追加されたライブラリ」には、テンプレート機能を使って作られた機能がたくさんあります。

ここからは、テンプレートの使い方の例として標準ライブラリの関数を取り上げ、それらの関数がどのようにテンプレートを利用しているかを解説します。

最初に紹介するのは`swap`(スワップ)関数です。この関数は、引数で渡された２つの変数の内容を入れ替えます。<br>
テンプレートを使った`swap`関数の定義は、次のようになります。

```cpp
template<typename T>
void swap(T& a, T& b) {
  T tmp = a;
  a = b;
  b = tmp;
}
```

入力データの型を「仮の型`T`」にしているので、どんな型であっても値を交換できます。

`swap`関数を使わない場合、例えば`int`型の変数の値を入れ替えるには、作業用の変数を使って次のようなコードを書く必要があります。

```cpp
int a = 1, b = 2; // 入れ替えたい変数
int tmp = a; // 入れ替え作業用の変数
a = b;
b = tmp;
```

対して、`swap`関数を使うと次のように書けます。<br>
作業用の変数が不要なだけでなく、`swap`という関数名によって「値を入れ替えたい」という意図が明確になっています。

```cpp
int a = 1, b = 2;
swap(a, b);
```

次のプログラムは、`swap`関数を使った例です。

**コード**

```cpp
#include <iostream>
#include <string>
#include <algorithm>
using namespace std;

int main() {
  int a = 1, b = 2;
  string s = "123", t = "abc";

  cout << "swap前:" << endl;
  cout << "  a=" << a << ", b=" << b << endl;
  cout << "  s=" << a << ", t=" << b << endl;

  swap(a, b); // T = intとして実行される
  swap(s, t); // T = stringとして実行される

  cout << "swap後:" << endl;
  cout << "  a=" << a << ", b=" << b << endl;
  cout << "  s=" << a << ", t=" << b << endl;
}
```

**実行結果**

```txt
swap前:
  a=1, b=2
  s=123, t=abc
swap後:
  a=2, b=1
  s=abc, t=123
```


### 3.4 min(ミン)関数とmax(マックス)関数

`min`関数は「２つ以上の値のうち、最も小さい値」を返す関数です。<br>
`max`関数はその逆で、「２つ以上の値のうち、最も大きい値」を返す関数です。<br>
もし2つの値が等しい場合は、どちらの関数も最初の値を返します。

テンプレートを使った`min`関数と`max`関数の定義は、次のようになります。

```cpp
template<typename T>
const T& min(const T& a, const T& b) {
  if (b < a) {
    return b;
  } else {
    return a;
  }
}

template<typename T>
const T& max(const T& a, const T& b) {
  if (b > a) {
    return b;
  } else {
    return a;
  }
}
```

`min`関数と `max`関数は、値の範囲を制限したい場合によく使われます。

例えば、`if`文を使って、「ある変数の値が最小値未満だったら最小値に、最大値より大きければ最大値にする」というプログラムは、よく見かけるものです。

次の例は、入力された値を0～100の範囲に制限して出力するプログラムです。

**コード**

```cpp
#include <iostream>
using namespace std;

int main() {
  int n;
  cin >> n;

  if (n < 0) {
    n = 0;
  } else if (n > 100) {
    n = 100;
  }

  cout << n << endl;
}
```

**入力例（１）**

```txt
-1
```

**出力例（１）**

```txt
0
```

**入力例（２）**

```txt
999
```

**出力例（２）**

```txt
100
```

`min`関数と`max`関数を使うと、この範囲制限プログラムは次のように書けます。

**コード**

```cpp
#include <iostream>
#include <algorithm>
using namespace std;

int main() {
  int n;
  cin >> n;

  n = max(n, 0);   // nと0のうち大きいほうを返す
  n = min(n, 100); // nと100のうち小さいほうを返す

  cout << n << endl;
}
```

３つ以上のデータの最小値、または最大値を求めるには、次のようにデータを`{}`で囲みます。

**コード**

```cpp
#include <iostream>
#include <algorithm>
using namespace std;

int main() {
  cout << max( { 1, 2, 3, 4, 5 } ) << endl;
  cout << min( { 1, 2, 3, 4, 5 } ) << endl;;
}
```

**実行結果**

```txt
5
1
```

>この例の`{}`の使い方について、詳しく知りたい場合は`initializer_list`(イニシャライザ・リスト)で検索してください。

また、コンテナから最小、最大を求めるには、`ranges`(レンジズ)ライブラリの`min`、`max`関数を使って次のように書きます。

**コード**

```cpp
#include <iostream>
#include <vector>
#include <algorithm>
using namespace std;

int main() {
  vector<int> v = { 1, 2, 3, 4, 5 };
  cout << ranges::max(v) << endl;
  cout << ranges::min(v) << endl;;
}
```

**実行結果**

```txt
5
1
```


### 3.5 find(ファインド)関数

`find`関数は「範囲内から指定された値を検索」します。値が等しいかどうかを調べるだけなので、プログラムは比較的簡単です。

テンプレートを使った`find`関数の定義は、基本的には次のようになります(実際の標準ライブラリのコードはもっと長いです)。

```cpp
template<typename Iter, typename T>
Iter find(Iter first, Iter last, const T& value)
{
  for (; first != last; ++first) {
    if (*first == value) {
      break;
    }
  }
  return first;
}
```

関数宣言を読み解くと、`find`関数とは、「`Iter`型の`first`から`last`の範囲より、`value`と一致する値を探して、見つかった位置を返す関数」となります。

「仮の型」は２つで、`Iter`(イテレータの略称で「イター」または「アイター」と読む)と、`T`(`Type`の頭文字「ティー」)です。

>**【仮の型の名前について】**<br>
>慣習的に、「仮の型」の名前は、頭文字、略称、短縮形などを使って短めにすることが多いです。<br>
>不完全な名前を使うことで「本物の型ではない」ことを示し、他の構造体や変数の名前と区別しやすくするためです。

テンプレート引数`Iter`を実際の型に置き換えるとき、その型は少なくとも以下の機能を持つ必要があります。

* `!=`演算子による比較
* `++`演算子によるインクリメント
* `*`演算子によるデータの読み取り

そして、これらの要件を満たす最も低機能のイテレータは「入力イテレータ」です。つまり、入力イテレータか、その上位の機能を持つイテレータを使うデータ構造であれば、`find`関数によってデータを検索できるわけです。

`find`関数の引数に、入力イテレータの要件を満たさない型の変数を指定すると、コンパイルエラーになります。

>`==`演算子による比較は`T`型の要件で、`Iter`の要件ではないことに注意。

例えば、`vector`型と`string`型の`begin`関数と`end`関数は「隣接イテレータ」を返します。イテレータの表を見ると、隣接イテレータは入力イテレータの機能を含むため、`find`関数を使えることが分かります。

**コード**

```cpp
#include <iostream>
#include <vector>
#include <string>
#include <algorithm>
using namespace std;

int main() {
  vector<int> v = { 2, 7, 1, 8, 2, 8, 1 };
  string s = "abcdefg";

  // v は vector<int> 型なので、 v.begin() は vector<int>::iterator 型のイテレータを返す
  // find 関数の仮の型 Iter は vector<int>::iterator になる
  auto i = find(v.begin(), v.end(), 8);

  // s は string 型なので、 s.begin() は string::iterator 型のイテレータを返す
  // find 関数の仮の型 Iter は string::iterator になる
  auto j = find(s.begin(), s.end(), 'f');

  cout << *i << endl;
  cout << *j << endl;
}
```

**実行結果**

```txt
8
f
```

なお、「範囲の先頭」と「範囲の終端」をあらわす2つのイテレータによって範囲を指定する手法は、`find`関数に限らず、標準ライブラリの多くの関数で使われています。


### 3.6 find_if(ファインド・イフ)関数

`find_if`関数の機能は、「範囲内から、条件を満たす値を見つける」というものです。<br>
2.3節で解説した`find`関数との違いは、検索する対象が「一致する値」か、「条件を満たす値」か、という点です。

テンプレートを使った`find_if`関数の定義は、次のようになります。

```cpp
template<typename Iter, typename P>
Iter find(Iter first, Iter last, P pred)
{
  for (; first != last; ++first) {
    if (pred(*first)) {
      break;
    }
  }
  return first;
}
```

`find_if`関数がやることは、次のとおりです。

1. 範囲の「先頭」から順番に「`pred`が`true`を返す(条件を満たす)値」を探す
2. 値を見つけたら、「最初に見つけた位置を示すイテレータ」を返す
3. 値を見つけられないまま「終端」まで来てしまったら、「終端」の位置を返す

「条件」は引数`pred`(プレド、「述語」を意味する`predicate`の短縮形)で指定します。`pred`に指定するのは、基本的には「関数」です。

`find_if`を使った例を次に示します。

```cpp
#include <iostream>
#include <vector>
#include <algorithm>
using namespace std;

// nが5より大きければtrueを返す関数
bool greater_than_five(int n) {
  return n > 5;
}

int main() {
  vector<int> v = { 3, 1, 4, 1, 5, 9, 2, 6 };

  auto i = find_if(v.begin(), v.end(), greater_than_five);

  cout << "5より大きい最初の数は" << *i << endl;
  cout << "位置は" << i - v.begin() << "番目" << endl;
}
```

**実行結果**

```txt
5より大きい最初の数は9
位置は5番目
```

このように、`find_if`関数は、「条件を関数として指定できる」ことで、さまざまな条件に対して汎用的に使える関数になっています。

とはいえ、汎用アルゴリズムを使うたびに「条件の関数」を定義するのは面倒です。そこで、「無名関数」という機能を使います。


#### 無名関数(むめいかんすう)

「無名関数」は、関数名の代わりに`[]`を使う記法です。基本的な書きかたは次のとおりです。

`[](引数リスト) { 関数のプログラム }`

例えば、「5より大きい」を判定する無名関数は次のようになります。

`[](int n) { return n > 5; }`

戻り値型は、`return`文から自動的に型が推定されます。上記の無名関数の場合、`n > 5`という条件式の結果は`bool`型です。つまり、戻り値型は`bool`型になります。

戻り値型を明示的に指定したい、例えば、なにかの事情で計算結果を`double`型で返したい場合は、次のように書きます。

`[](int n) -> double { return n > 5; }`

次のプログラムは、前に書いた`find_if`の例を、無名関数を使って書き直したものです。

**コード**

```cpp
#include <iostream>
#include <vector>
#include <algorithm>
using namespace std;

int main() {
  vector<int> v = { 3, 1, 4, 1, 5, 9, 2, 6 };

  auto i = find_if(v.begin(), v.end(), [](int n) { return n > 5; });

  cout << "5より大きい最初の数は" << *i << endl;
  cout << "位置は" << distance(v.begin(), i) << "番目" << endl;
}
```

**実行結果**

```txt
5より大きい最初の数は9
位置は5番目
```

`greater_than_five`関数の定義がなくなり、代わりに`find_if`の「条件」部分に、無名関数を直接書いていることに注目してください。

無名関数に変数を渡したい場合は、`[]`の内側に渡したい変数名を書きます。この機能を「キャプチャ」といいます。

キャプチャを使った例を次に示します。

**コード**

```cpp
#include <iostream>
#include <vector>
#include <algorithm>
using namespace std;

int main() {
  vector<int> v = { 1, 4, 1, 4, 2, 1, 3, 5, 6 };

  int x;
  cin >> x;

  auto i = find_if(v.begin(), v.end(), [x](int n) { return n > x; });

  cout << x << "より大きい最初の数は" << *i << endl;
}
```

**入力例（１）**

```txt
5
```

**出力例（１）**

```txt
5より大きい最初の数は6
```

**入力例（２）**

```txt
3
```

**出力例（２）**

```txt
3より大きい最初の数は4
```

このように、汎用アルゴリズムに無名関数を組み合わせると、やりたいことをひとつの行にまとめられます。<br>
結果として、読み書きや変更が簡単になります。


### 3.7 copy(コピー)関数

`copy`関数は、複数のデータを先頭から終端に向かって順番にコピーします。<br>
テンプレートを使った`copy`関数の定義は、次のようになります。

```cpp
template<typename Iter1, typename Iter2>
Iter2 copy(Iter1 first, Iter1 last, Iter2 result)
{
  for (; first != last; ++first, ++result) {
    *result = *first;
  }
  return result;
}
```

`copy`関数の「仮の型」は`Iter1`(アイター1)と`Iter2`(アイター2)の2つです。`Iter1`型には以下の機能が必要です。

* `!=`演算子による比較
* `++`演算子によるインクリメント
* `*`演算子によるデータの読み取り

この要件は`find`関数の「仮の型」と同じなので、`Iter1`には「入力イテレータ」の機能が必要になります。

そして、`Iter2`には以下の機能が必要です。

* `++`演算子によるインクリメント
* `*`演算子によるデータの書き込み

こちらの要件を満たすのは「出力イテレータ」です。<br>
つまり、`copy`関数は「入力イテレータからデータを読み取り、出力イテレータへデータを書き込む関数」といえます。

注意点として、`first`から`last`のあいだに`result`が含まれていてはなりません。もし含まれていると、コピーが正しく行われません。

次の例は、`copy`関数を使ったプログラムです。

**コード**

```cpp
#include <iostream>
#include <vector>
#include <algorithm>
using namespace std;

int main() {
  vector<int> a = { 1, 2, 3, 4, 5, 6, 7, 8 };

  copy(a.begin() + 2, a.end(), a.begin());

  for (int i = 0; i < (int)a.size(); i++) {
    cout << a[i] << " ";
  }
  cout << endl;
}
```

**実行結果**

```txt
3 4 5 6 7 8 7 8
```


### 3.8 copy_backward(コピー・バックワード)関数

`copy_backward`関数は、複数のデータを終端から先頭に向かって順番にコピーします。`copy`関数とはコピーの順序が違うだけです。

```cpp
template<typename Iter1, typename Iter2>
Iter2 copy_backward(Iter1 first, Iter1 last, Iter2 result)
{
  for (; first != last;) {
    --last;
    --result;
    *result = *last;
  }
  return result;
}
```

`copy_backward`関数の「仮の型」は`Iter1`(アイター1)と`Iter2`(アイター2)の2つです。`Iter1`型には以下の機能が必要です。

* `!=`演算子による比較
* `--`演算子によるデクリメント
* `*`演算子によるデータの読み取り

`--`演算子が使えるのは「双方向イテレータ」なので、`Iter1`は「双方向イテレータ」になります。

そして、`Iter2`には以下の機能が必要です。

* `--`演算子によるインクリメント
* `*`演算子によるデータの書き込み

こちらも、`--`演算子が必要なことから、要件を満たすのは「双方向イテレータ」となります。

それから、`copy`関数と同じく、`first`から`last`のあいだに`result`が含まれていてはなりません。もし含まれていると、コピーが正しく行われません。

次のプログラムは、`copy_backward`関数を使った例です。

**コード**

```cpp
#include <iostream>
#include <vector>
#include <algorithm>
using namespace std;

int main() {
  vector<int> a = { 1, 2, 3, 4, 5, 6, 7, 8 };

  copy_backward(a.begin(), a.end() - 2, a.end());

  for (int i = 0; i < (int)a.size(); i++) {
    cout << a[i] << " ";
  }
  cout << endl;
}
```

**実行結果**

```txt
1 2 1 2 3 4 5 6
```

コピーするとき、どちらの関数を使うかは、次のように決めるとよいでしょう。

* コピー先の先頭がコピー元の範囲にない場合 → `copy`関数を使う
* それ以外の場合 → `copy_backward`関数を使う


### 3.9 reverse(リバース)関数

`reverse`関数は、範囲内のデータの並び順を逆にします。<br>
テンプレートを使った`reverse`関数の定義は、次のようになります。

```cpp
template<typename Iter>
void reverse(Iter first, Iter last)
{
  for (; first != last; ++first) {
    --last;
    if (first == last) {
      break;
    }

    const auto tmp = *last;
    *last = *first;
    *first = tmp;
  }
}
```

`reverse`関数の「仮の型」である`Iter`には、以下の機能が必要です。

* `!=`演算子による比較
* `++`演算子によるインクリメント
* `--`演算子によるデクリメント
* `*`演算子によるデータの読み取り、および書き込み

つまり、`reverse`関数のテンプレート引数`Iter`は、この要件を満たす「双方向イテレータ」の機能を持っている必要があります。

次の例は、`reverse`関数を使ったプログラムです。

**コード**

```cpp
#include <iostream>
#include <vector>
#include <algorithm>
using namespace std;

int main() {
  vector<int> v = { 1, 2, 3, 4, 5 };

  reverse(v.begin(), v.end());

  for (auto i = v.begin(); i != v.end(); i++) {
    cout << *i << ' ';
  }
  cout << endl;
}
```

**実行結果**

```txt
5 4 3 2 1
```

また、`ranges`ライブラリを使うともう少し短く、次のように書けます。

**コード**

```cpp
#include <iostream>
#include <vector>
#include <algorithm>
using namespace std;

int main() {
  vector<int> v = { 1, 2, 3, 4, 5 };

  ranges::reverse(v);

  for (auto i = v.begin(); i != v.end(); i++) {
    cout << *i << ' ';
  }
  cout << endl;
}
```

**実行結果**

```txt
5 4 3 2 1
```

コンテナ全体を反転させたい場合は`ranges::reverse`を使い、コンテナの一部分(例えば最初の5つの要素)だけを反転させたい場合は通常の`reverse`を使うとよいでしょう。


### 3.10 sort(ソート)関数

`sort`関数は、範囲内のデータを昇順、つまり小さい順に並べ替えます。

`sort`関数の書き方は2つあり、それぞれ次のように書きます(定義は長くなるので省略)。

```cpp
template<typename Iter>
void sort(Iter first, Iter last);

template<typename Iter, typename C>
void sort(Iter first, Iter last, C comp);
```

最初の書きかたから見ていきましょう。このバージョンの`sort`関数は、次のように使います。

**コード**

```cpp
#include <iostream>
#include <vector>
#include <algorithm>
using namespace std;

int main() {
  vector<int> v = { 1, 7, 3, 2, 0, 5, 0, 8 };

  sort(v.begin(), v.end());

  for (auto i = v.begin(); i != v.end(); i++) {
    cout << *i << ' ';
  }
  cout << endl;
}
```

**実行結果**

```txt
0 0 1 2 3 5 7 8
```

昇順ではなく、降順に並べ替えたい場合は2つめのバージョンを使います。これは、次のようなプログラムになります。

**コード**

```cpp
#include <iostream>
#include <vector>
#include <algorithm>
using namespace std;

int main() {
  vector<int> v = { 1, 7, 3, 2, 0, 5, 0, 8 };

  sort(v.begin(), v.end(), [](int a, int b) { return a > b; });

  for (auto i = v.begin(); i != v.end(); i++) {
    cout << *i << ' ';
  }
  cout << endl;
}
```

**実行結果**

```txt
8 7 5 3 2 1 0 0
```

このプログラムでは次の無名関数を使用しています。

`[](int a, int b) { return a > b; }`

この関数の内容は、「前にある数値のほうが大きい場合に`true`、そうでなければ`false`を返す」というものです。

ピンときたかもしれませんが、次のような無名関数を与えると、最初のバージョンの`sort`と同じ動作になります。

```cpp
sort(v.begin(), v.end(), [](int a, int b) { return a < b; });
```

>**【stable_sort(ステーブル・ソート)関数について】**<br>
>`sort`関数の欠点は、「等しいと判定されたデータ同士の順序が毎回異なる」点です。もし、「等しいと判定されたデータ同士は並べ替え前の順番どおりになってほしい」場合は、代わりに`stable_sort`という関数を使います。
>
>例えば、名前と得点を持つ構造体があり、得点の小さい順に並べ替えたい場合を考えます。鈴木さんと佐藤さんの得点が同じ場合に、データが登録順になってほしいなら`stable_sort`を使い、順番がどうなってもよいなら`sort`を使います。


### 3.11 remove_if(リムーブ・イフ)関数

`remove_if`関数の目的は「特定のデータの削除」ですが、実は次のように少し変わった動作をします。

1. 範囲内のデータを先頭から調べ、条件を「満たさない」データだけを前側に集める
2. 条件を満たすデータは、満たさないデータより後ろ側に残される
3. すべてのデータを調べ終わったら、条件を満たすデータの先頭の位置を返す

つまり、`remove_if`関数は「実際にはデータを削除しない」のです。データの削除にはコンテナ自体が必要ですが、汎用アルゴリズムが受け取るのはイテレータなので、削除できないのです。イテレータにできるのは「要素を移動させる」ことだけです。

そこで`remove_if`関数は、削除したくない、つまり条件を「満たさない」データを範囲の前側に移動させます。全て移動させると、後ろ側には削除したいデータだけが残ります。あとは、削除したいデータの位置を返して、実際の削除はプログラマに任せます。

データを削除するには、コンテナの`erase`関数を使います。

説明だけだと分かりにくいので、配列から偶数を削除する場合の`remove_if`関数の動作例を、以下に示します。

1. 最初の位置を調べる。8は偶数なので削除対象。上書き可能な場所としてマークする。
   ```txt
                     x(上書き可能マーク)
   [8 3 2 2 1 5] -> [8 3 2 2 1 5]
    ^(調べる位置)    ^
   ```
2. 次の位置を調べる。3は奇数なので残す。上書き可能な場所があるのでコピーし、元に位置を上書き可能とマークする。
   ```txt
    x                                   x
   [8 3 2 2 1 5] -> [3 3 2 2 1 5] -> [3 3 2 2 1 5]
      ^                ^                ^
   ```
3. 次の位置を調べる。2は偶数なので削除対象。上書き可能とマークする。
   ```txt
      x                x x
   [3 3 2 2 1 5] -> [3 3 2 2 1 5]
        ^                ^
   ```
4. 次の位置を調べる。2は偶数なので削除対象。上書き可能とマークする。
   ```txt
      x x              x x x
   [3 3 2 2 1 5] -> [3 3 2 2 1 5]
          ^                ^
   ```
5. 次の位置を調べる。1は奇数なので残す。上書き可能な場所にコピーし、元の位置を上書き可能とマークする。
   ```txt
      x x x              x x              x x x
   [3 3 2 2 1 5] -> [3 1 2 2 1 5] -> [3 1 2 2 1 5]
            ^                ^                ^
   ```
6. 次の位置を調べる。5は奇数なので残す。上書き可能な場所にコピーし、元の位置を上書き可能としてマークする。
   ```txt
        x x x              x x              x x x
   [3 1 2 2 1 5] -> [3 1 5 2 1 5] -> [3 1 5 2 1 5]
              ^                ^                ^
   ```
7. 最後まで調べ終わったので、上書き可能としてマークされた最初の位置を返す。
   ```txt
          x x x
   [3 1 5 2 1 5]
          ^(この位置を戻り値にする)
   ```

続いて、実際のプログラムを見てみましょう。次のプログラムは、配列から偶数の要素を削除します。

**コード**

```cpp
#include <iostream>
#include <vector>
#include <algorithm>
using namespace std;

int main() {
  vector<int> v = { 1, 4, 1, 4, 2, 1, 3, 5, 6 };

  // 奇数の要素を前側に集める
  // 戻り値iには、削除するべきデータの先頭位置が代入される
  auto i = remove_if(v.begin(), v.end(), [](int n) { return n % 2 == 0; });

  // 位置iから最後のデータまでを削除
  v.erase(i, v.end());

  // 残ったデータを出力
  for (auto j = v.begin(); j != v.end(); j++) {
    cout << *j << ' ';
  }
  cout << endl;
}
```

**実行結果**

```txt
1 1 1 3 5
```

上の例は動作を分かりやすくするために`remove_if`と`erase`を別々の行に分けましたが、通常は次のようにまとめて書くことが多いです。

**コード**

```cpp
#include <iostream>
#include <vector>
#include <algorithm>
using namespace std;

int main() {
  vector<int> v = { 1, 4, 1, 4, 2, 1, 3, 5, 6 };

  v.erase(
    remove_if(v.begin(), v.end(), [](int n) { return n % 2 == 0; }),
    v.end());

  for (auto j = v.begin(); j != v.end(); j++) {
    cout << *j << ' ';
  }
  cout << endl;
}
```

このような、汎用アルゴリズムの`remove_if`関数と、コンテナの`erase`関数を組み合わせて使うことは、データを削除する定番の書きかた(イディオム)です。C++プログラマのあいだでは、この書きかたには「`erase-remove`(イレース・リムーブ)イディオム」という名前がついています。


### 3.12 unique(ユニーク)関数

`unique`関数の機能は、「範囲から重複するデータをなくして、唯一の(つまり、ユニークな)データだけにする」ことです。ですが、`remove_if`関数でも解説したように、汎用アルゴリズムはコンテナの要素を削除できません。

そのため、`unique`関数が実際に行うのは、`remove_if`と同様の「削除しないデータを範囲の前方に集める」という処理です。

1. 範囲内のデータを先頭から調べ、「隣り合う等しいデータ」を見つけたら、先頭のデータだけを前側に集める
2. 残りのデータは後ろ側に残される
3. すべてのデータを調べ終わったら、集めなかったデータの先頭の位置を返す

実際のデータの削除には、コンテナの`erase`関数を使います。

また、重複していると判定できるのは「隣り合う等しいデータ」に限られます。例えば、次のようなデータがあるとします。

`1 1 7 1 1 1 3 3`

このデータ全体に対して`erase`と`unique`を実行すると、次の結果になります。

`1 7 1 3`

この例では、最初の2つの`1`と、`7`の次から始まる3つの`1`は、途中の`7`で分断されて2つのグループになっています。<br>
そのため、グループごとにユニークなデータが残されて、`1`が2つ残ってしまうのです。

名前のとおりに「ユニークなデータ」だけを残すには、事前に等しいデータが全て隣接するように並べ替えておく必要があります。<br>
この並べ替えは、`sort`関数を使えば簡単にできます。

`sort`関数を使って前のデータを並べ替えると、次のようになります。

`1 1 1 1 1 3 3 7`

この状態にしてから`erase`と`unique`を実行すれば、次のように「ユニークなデータだけ」の結果が得られます。

`1 3 7`

次の例は、`unique`、`erase`、`sort`を組み合わせて重複をなくすプログラムです。

**コード**

```cpp
#include <iostream>
#include <vector>
#include <algorithm>
using namespace std;

int main() {
  vector<int> v = { 2, 7, 1, 8, 2, 8, 1, 8, 2, 8, 4, 5, 9, 0, 4 };

  sort(v.begin(), v.end());
  v.erase(unique(v.begin(), v.end()), v.end());

  for (auto j = v.begin(); j != v.end(); j++) {
    cout << *j << ' ';
  }
  cout << endl;
}
```

**実行結果**

```txt
0 1 2 4 5 7 8 9
```


----

## 4 練習問題

----

以下の手順にしたがって、各問題のプログラムを完成させなさい。

1. `%%writefile ...`の下の行からがプログラムです。問題文に従ってプログラムを修正、または追加してください。
2. プログラムを修正したら、セルの右側にある`▶`をクリックします。すると、ファイルが保存されます。
3. 「動作テスト」セルの`▶`をクリックすると、2で保存したファイルがコンパイル＆実行され、実行結果が表示されます。<br>
   このセルは、修正したプログラムの動作を確認するために使ってください。
4. 「実行」セルの`▶`をクリックすると、2で保存したファイルがコンパイル＆実行され、結果の成否が判定されます。
5. 判定に成功したら`AC`と表示されます。次の問題に進んでください。
6. 失敗したら`WA`と表示されます(その前にエラーメッセージが表示される場合もあります)。<br>
   これは、プログラムのどこかにエラーがあることを意味します。<br>
   「動作テスト」を使ってエラーを修正し、`AC`を目指してください。


### ❓️問題１

1個の文字列が入力されます。<br>
入力された文字列が`dog`のときは`ワンワン`、`cat`のときは`ニャーニャー`、それ以外のときは`ガオー`と出力するプログラムを作成しなさい。

| 入力 | 出力する文字列 |
|:----:|:---------------|
| <font size=2>dog</font> | ワンワン     |
| <font size=2>cat</font> | ニャーニャー |
| その他                  | ガオー       |

<br><details><summary>🗝️(クリックでヒントを見る)</summary>

**プログラム例**

1. `string`型の変数`s`を定義する
2. if文を使って、`s`が文字列`dog`と等しい場合は、標準出力`cout`に文字列`ワンワン`を出力する
3. else if文を使って、`s`が文字列`cat`と等しい場合は、標準出力`cout`に文字列`ニャーニャー`を出力する
4. else句を使って、標準出力`cout`に文字列`ガオー`を出力する

</details><br>

**入力データ例（１）**

```
dog
```

**出力例（１）**

```txt
ワンワン
```

**入力データ例（２）**

```
cat
```

**出力例（２）**

```txt
ニャーニャー
```

**入力データ例（３）**

```
doggie
```

**出力例（３）**

```txt
ガオー
```


In [ ]:
%%writefile practice_01a.cpp
#include <iostream>
#include <string>
using namespace std;

int main() {
  // この下に、文字列を読み込んで鳴き声を出力するプログラムを書く

}

In [ ]:
# @title 動作テスト
!g++ -std=c++20 -O2 -Wall -Wextra -o practice_01a practice_01a.cpp && echo "この下をクリックして、動物の名前を入力" && ./practice_01a

In [ ]:
# @title 実行
!diff -Z <(echo -e "ワンワン\nニャーニャー\nガオー") <(g++ -std=c++20 -O2 -Wall -Wextra -o practice_01a practice_01a.cpp && echo "dog" | ./practice_01a && echo "cat" | ./practice_01a && echo "human" | ./practice_01a) > nil && test $? -eq 0 && echo -e "\033[32;1mAC" || echo -e "\033[31;1mWA"

In [ ]:
# @title 🔒解答例(どうしても問題を解けない場合に見てください)
%%writefile practice_01a.cpp
#include <iostream>
#include <string>
using namespace std;

int main() {
  // この下に、文字列を読み込んで鳴き声を出力するプログラムを書く
  string s;
  cin >> s;

  if (s == "dog") {
    cout << "ワンワン" << endl;
  } else if (s == "cat") {
    cout << "ニャーニャー" << endl;
  } else {
    cout << "ガオー" << endl;
  }
}