# 標準ライブラリ その１


## キーポイント

* コンテナは、複数のデータを利用しやすい形式で格納するクラス
* `vector`や`string`もコンテナの一種
* イテレータは、コンテナ内のデータの位置を示すクラスで、ポインタと似ている
* イテレータは、コンテナの種類が違っても同じように使えるが、添え字は一部のコンテナでしか使えない
* 汎用アルゴリズムは、イテレータを介してコンテナを操作する関数で、さまざまな種類がある
* 三角関数のような一般的な数学関数は標準ライブラリに定義されているので、自分で書く必要はない
* 無名関数(ラムダ式)を使うと、汎用ライブラリの判定条件を自由に作成できる


----

## 1 標準ライブラリの構成要素

----


### 1.1 標準ライブラリとは

>**【注意事項】**<br>
>本テキストの内容はC++20バージョンを前提にしています。<br>
>古いバージョンのC++では、一部の機能が使えない場合があります。

C++標準ライブラリは、プログラミングにおける一般的な問題を解決するためによく使われる機能を、型(クラス)や関数、変数として定義し、それらをまとめたものです。

C++標準ライブラリには、以下の機能が含まれます。

* **コンテナ：** 複数のデータを利用しやすい形式で格納する
* **イテレータ：** コンテナ内のデータの位置を示す
* **汎用アルゴリズム：** イテレータを介してコンテナを操作する
* **文字列の入出力：** 文字の操作と入出力を行う(`string`や`cin`、`cout`などを含む)
* **数値計算などの一般的な関数：** べき乗、平方根、複素数、乱数など
* **C++の言語能力を拡張するための機能：** スマートポインタ、デバッグ支援、数値型の制限情報、例外処理など

標準ライブラリのほぼすべての機能は、`std`(エス・ティー・ディー)という「名前空間」に属します。

名前空間の目的は、「プログラムの機能をグループ階層に振り分けて、プログラム全体を管理しやすくすること」です。<br>
異なる名前空間にある変数や関数の識別は、所属する名前空間を`::`記号で区切って指定することで行います。例えば、標準ライブラリの`string`型を正確に表す書きかたは次のようになります。

`std::string`

>`::`記号は「スコープ解決演算子」と呼ばれます。


### 1.2 コンテナ

コンテナは「複数のデータを利用しやすい形式で格納する型」です。<br>
次の表は、標準ライブラリに用意されている主要なコンテナです(コンテナは他にもあります)。

| コンテナ名 | 機能 |
|:-----------|:-----|
| vector(ベクター)                      | 配列 |
| string(ストリング)                    | 文字列     |
| unordered_map(アンオーダード・マップ) | 連想配列   |
| list(リスト)                          | 連結リスト |
| deque(デック)                         | 両端キュー |

これらのコンテナは、以下の3つの機能を持ちます。


#### 格納されたデータを読み書きする機能

コンテナは、コンテナに格納されたデータを読み書きする機能を持っています。基本的に、読み書きは`[]`記号と添え字を使うことで行われます。

添字が使えないのコンテナの場合は、代わりにあとで説明する「イテレータ」を使います。

また、特定の位置のデータを簡単に読み書きする機能が用意されているコンテナもあります。例えば、`vector`や`string`には、先頭のデータを読み書きできる`front`メンバ関数、末尾のデータを読み書きできる`back`メンバ関数が用意されています。

**コード**

```cpp
#include <iostream>
#include <vector>
using namespace std;

int main() {
  vector<int> v = { 1, 2, 3, 4, 5 };
  cout << v[2] << endl;
  cout << v.front() << endl;
  cout << v.back() << endl;
}
```

**実行結果**

```txt
3
1
5
```


#### データを処理するためのメンバ関数

いくつかのコンテナには、格納されているデータを検索したり、データを置き換えたりするメンバ関数が用意されています。

例えば、`string`には、文字列を置換するための`replace`(リプレース)関数が用意されています。

**コード**

```cpp
#include <iostream>
#incluce <string>
using namespace std;

int main() {
  string s = "012345";
  // 2文字目から3つの文字をTwoThreeFourに置き換える
  s.replace(2, 3, "TwoThreeFour");
  cout << s << endl;
}
```

**実行結果**

```txt
01TwoThreeFour5
```


#### データを記録するためのメモリ領域の管理

`int`のような組み込み型の変数では、必要なメモリ、つまりメモ帳の行数は、整数ひとつを記録できる程度です(メモ帳の1行分くらい)。

しかし、`vector`や`string`のようなコンテナは、いくつでもデータを格納できます。さらに、格納しているデータを削除したり、新しく追加することもできます。メモ帳で例えると、ひとつのページを丸ごとコンテナ用に予約しているようなものです。

データが追加されて1ページで足りなくなったら、メモ帳の最後からページを抜き取ってコンテナのページの後ろに追加します(コンピューター上のメモ帳は、ページを外したり追加したりできるのです)。

なお、予約されているメモリ量は、`capacity`(キャパシティ)関数で調べられます。

**コード**

```cpp
#include <iostream>
#include <vector>
using namespace std;

int main() {
  vector<int> v = { 1, 2, 3 };
  cout << "push_back前のキャパシティ:" << v.capacity() << endl;
  v.push_back(4);
  cout << "push_back後のキャパシティ:" << v.capacity() << endl;
}
```

**実行結果**

```txt
push_back前のキャパシティ:3
push_back後のキャパシティ:6
```

### 1.3 イテレータ

イテレータは「ポインタの機能を要件ごとに分類して名前をつけたもの」で、日本語では「反復子(はんぷくし)」と呼ばれます。<br>
イテレータの目的は、さまざまなコンテナを共通の方法で処理できるようにすることです。

イテレータには複数の種類があり、種類ごとに機能要件が定められています。<br>
以下に、実際にコンテナで使われている4種類のイテレータの概要を示します。

| 種類 | 機能要件 | 対応するコンテナ |
|:-----|:-----|:---------------------|
| 前方向イテレータ | データの読み書き、イテレータ同士の比較、<br>位置をひとつ進めること(インクリメント)ができる | unordered_map |
| 双方向イテレータ | 前方向イテレータの機能に加えて、位置をひとつ戻すこと(デクリメント)ができる | list |
| ランダム・アクセス・イテレータ | 双方向イテレータの機能に加えて、位置を自由に変更(位置に整数を足し引き)すること、<br>2つのイテレータの距離を計算することができる | deque |
| 隣接イテレータ | ランダム・アクセス・イテレータの機能に加えて、<br>イテレータの指す要素が連続していることを保証する(ポインタと互換性がある) | vector, string |

イテレータの種類ごとの関係は、次の図のようになります。

$$
\boxed{
  　隣接イテレータ(ポインタ) \\
  \boxed{
      ランダムアクセスイテレータ \\
    \boxed {
    \space　　双方向イテレータ \\
      \boxed {
        　　前方向イテレータ
      }
    }
  }
}
$$

例えば、ランダムアクセスイテレータは自身の機能に加えて、双方向イテレータと前方向イテレータの機能も持ちます。<br>
ですが、双方向イテレータはランダムアクセスイテレータの機能を持ちません。

#### コンテナからイテレータを得る方法

ほとんどのコンテナには、「保持しているデータを指すイテレータ」を取得する関数があります。

コンテナが保持する複数のデータに対して、データ範囲の先頭と終端の２種類のイテレータを取得できます。

* `begin`(ビギン)関数: データ範囲の先頭のイテレータを取得する。
* `end`(エンド)関数: データ範囲の終端のイテレータを取得する。

取得したイテレータを先頭から終端までインクリメントすることで、コンテナ全体を処理できます。<br>
以下は、イテレータを使ったfor文の例です。`vector<int>::iterator`は、`vector<int>`用のイテレータ型です。

**コード**

```cpp
#include <iostream>
#include <vector>
using namespace std;

int main() {
  vector<int> v = { 1, 4, 1, 4, 2, 1, 3, 5, 6 };

  for (vector<int>::iterator i = v.begin(); i != v.end(); i++) {
    cout << *i << ' ';
  }
  cout << endl;
}
```

**実行結果**

```txt
1 4 1 4 2 1 3 5 6
```

イテレータが指すデータを読み書きするには、ポインタと同様に`*`(アスタリスク)を使います。上のプログラムでは`*i`の部分でデータを読み出しています。


#### auto(オート)キーワード

イテレータ型には、長い名前のものが多いので、書くのが大変です。例えば`vector<int>`型用のイテレータの名前は、

`vector<int>::iterator`

なのでした。入力支援があったとしても、この長さの名前を何度も書きたい、という人は少ないと思います。

そこで、`auto`(オート)キーワードの出番です。`auto`キーワードの機能は「初期値から型を推測する」ことです。

**コード**

```cpp
#include <iostream>
#include <vector>
using namespace std;

int main() {
  vector<int> v = { 1, 4, 1, 4, 2, 1, 3, 5, 6 };

  for (auto i = v.begin(); i != v.end(); i++) {
    cout << *i << ' ';
  }
  cout << endl;
}
```

変数`i`は`v.begin()`の戻り値で初期化されています。<br>
`auto`キーワードは`v.begin()`の戻り値型をチェックして、変数`i`の型を`vector<int>::iterator`だと推測します。


### 1.4 汎用アルゴリズム

汎用アルゴリズムは「イテレータを介してコンテナを操作する関数」です。<br>
「アルゴリズム」という用語は、「問題を解決するための段階的な手順」という意味です。<br>
また、「汎用」という名称は、コンテナの種類が違っても同じ関数が使えることが由来です。

多くの汎用アルゴリズムは、操作する範囲の「先頭」と「終端」を示す2つのイテレータを引数として受け取ります。<br>
アルゴリズムによっては、追加の引数がある場合もあります。

以下に、よく使われる汎用アルゴリズム関数の概要を示します。<br>
これらの汎用アルゴリズムは`algorithm`(アルゴリズム)ヘッダをインクルードすることで利用可能になります。

>2025年現在、C++には100種類以上の汎用アルゴリズムが定義されています。

| 関数名 | 概要 |
|:-------|:-----|
| find_if(ファインド) | 範囲内から指定された条件を満たすデータを見つける |
| count(カウント) | 範囲内にある指定されたデータの個数を数える |
| sort(ソート) | 範囲内のデータを昇順に並べ替える |
| lower_bound(ローワー・バウンド) | ソート済み範囲を効率的に検索する |
| reverse(リバース) | 範囲内のデータの並び順を逆にする |
| replace(リプレイス) | 範囲内の指定されたデータを別のデータで上書きする |
| remove_if(リムーブ・イフ) | 範囲内の指定されたデータを削除する |
| equal(イコール) | 2つの範囲の要素が等しいか判定する |
| unique(ユニーク) | 隣り合う同じデータをひとつにまとめる |
| accumulate(アキュムレート) | 範囲内のデータを合計する |
| min_element(ミン・エレメント) | 範囲内の最小のデータを検索する |
| swap(スワップ) | 2つの変数の内容を入れ替える |
| min(ミン) | 2つの変数のうち小さいほうを返す |
| max(マックス) | 2つの変数のうち大きいほうを返す |

>**【ranges(レンジズ)】**<br>
>C++20から、範囲ではなくコンテナ自体を引数として受け取り、コンテナ全体にアルゴリズムを実行する`ranges`(レンジズ)という機能が追加されました。


#### 汎用アルゴリズムと関数を組み合わせる

汎用アルゴリズムには「引数として関数を受け取る」関数が多いです。例として、データを検索する`find_if`関数を見てみましょう。`find_if`関数の宣言は、要約すると次のようになります。

`見つけた位置 find_if(範囲の先頭, 範囲の終端, 条件)`

「条件」には「関数」を指定します。例えば「5より大きい」データを見つけたい場合は、次のようなプログラムになります。

**コード**

```cpp
#include <iostream>
#include <vector>
#include <algorithm>
using namespace std;

bool greater_than_five(int n) {
  return n > 5;
}

int main() {
  vector<int> v = { 1, 4, 1, 4, 2, 1, 3, 5, 6 };

  auto i = find_if(v.begin(), v.end(), greater_than_five);

  cout << *i << endl;
}
```

**実行結果**

```txt
6
```

このように、`find_if`関数は「範囲内にある、条件を満たす値を見つける」という機能のうち、「条件」の部分を外から指定できるようにしたものです。この仕組みにより、さまざまな条件に対して汎用的に使える関数になっているのです。

ですが、汎用アルゴリズムを使うたびに引数用の関数を定義するのは面倒です。そこで、「無名関数」を使います。


#### 無名関数(むめいかんすう)

「無名関数」は、関数名の代わりに`[]`を使う記法です。基本的な書きかたは次のとおりです。

`[](引数リスト) { 関数のプログラム }`

例えば、「5より大きい」を判定する無名関数は次のようになります。

`[](int n) { return n > 5; }`

戻り値型は、`return`文から自動的に型が推定されます。上記の無名関数の場合、`n > 5`という条件式の結果は`bool`型です。つまり、戻り値型は`bool`型になります。

戻り値型を明示的に指定したい、例えば、なにかの事情で計算結果を`double`型で返したい場合は、次のように書きます。

`[](int n) -> double { return n > 5; }`

次のプログラムは、前に書いた`find_if`の例を、無名関数を使って書き直したものです。

**コード**

```cpp
#include <iostream>
#include <vector>
#include <algorithm>
using namespace std;

int main() {
  vector<int> v = { 1, 4, 1, 4, 2, 1, 3, 5, 6 };

  auto i = find_if(v.begin(), v.end(), [](int n) { return n > 5; });

  cout << *i << endl;
}
```

**実行結果**

```txt
6
```

`greater_than_five`関数の定義がなくなり、代わりに`find_if`の「条件」部分に、無名関数を直接書いていることに注目してください。

無名関数に変数を渡したい場合は、`[]`の内側に渡したい変数名を書きます。この機能を「キャプチャ」といいます。

キャプチャを使った例を次に示します。

**コード**

```cpp
#include <iostream>
#include <vector>
#include <algorithm>
using namespace std;

int main() {
  vector<int> v = { 1, 4, 1, 4, 2, 1, 3, 5, 6 };

  int x;
  cin >> x;

  auto i = find_if(v.begin(), v.end(), [x](int n) { return n > x; });

  cout << x << "より大きい最初の数は" << *i << endl;
}
```

**入力例（１）**

```txt
5
```

**出力例（１）**

```txt
5より大きい最初の数は6
```

**入力例（２）**

```txt
3
```

**出力例（２）**

```txt
3より大きい最初の数は4
```

このように、汎用アルゴリズムに無名関数を組み合わせると、やりたいことが同じ行にまとめられます。<br>
結果として、読み書きや変更が簡単になります。


### 1.5 文字列の入出力

これまで使ってきた`string`型や、`cin`(シー・イン)、`cout`(シー・アウト)なども、標準ライブラリの一部です。

`cin`と`cout`は、実際には`istream`(アイ・ストリーム)型と`ostream`(オー・ストリーム)型の変数です。<br>
これらの型は、「ストリーム」と呼ばれる「データ(主に文字)の流れ」を扱います。

文字列やストリームを扱うヘッダファイルの一覧:

| ヘッダファイル名 | 概要 |
|:-------------|:-----|
| string(ストリング) | 文字列を扱う |
| istream(アイ・ストリーム) | 外部からデータを読み込むストリーム |
| ostream(オー・ストリーム) | 外部にデータを出力するストリーム |
| fstream(エフ・ストリーム) | ファイルの読み書きに使うストリーム |
| sstream(エス・ストリーム) | 文字列をストリームに変換したり、ストリームを文字列に変換する |
| format(フォーマット) | 文字列をルールに従って変換する |
| regex(リジェックス) | 「正規表現」という文字列を検索するルールを扱う |
| filesystem(ファイル・システム) | コンピューター上にあるファイル情報を取得 |


### 1.6 数値計算などの一般的な関数

標準ライブラリには、数値計算でよく使われるさまざまな関数も定義されています。<br>
以下に一般的な数学関数の概要を示します。標準ライブラリには、これら以外にも多数の関数が定義されています。

| 関数 | 概要 |
|:-----|:-----|
| pow(x, y) | xのy乗 |
| sqrt(x)   | xの平方根 |
| sin(x)    | xの正弦(サイン) |
| cos(x)    | xの余弦(コサイン) |
| tan(x)    | xの正接(タンジェント) |
| log10(x)  | xの対数 |
| abs(x)    | xの絶対値 |
| fmod(x, y)| `x/y`の余り |
| ceil(x)   | x以上の最小の整数 |
| floor(x)  | x以下の最大の整数 |

また、乱数や統計を扱うための機能も含まれます。

主要なC++乱数ライブラリ:

| ライブラリ名 | 概要 |
|:-----|:-----|
| random_device(ランダム・デバイス) | (実装で可能な限り)真の乱数を生成 |
| mt1997<br>(エムティー・いちきゅうきゅうなな) | なんかいい感じの疑似乱数を生成 |
| rand(ランド) | C由来の疑似乱数 |
| minstd_rand(ミン・スタンダード・ランド) | Cのrandのパラメータを改良したもの |

主要な統計ライブラリ:

| ライブラリ名 | 概要 |
|:-----|:-----|
| uniform_int_distribution<br>(ユニフォーム・イント・ディストリビューション) | 整数の一様分布 |
| uniform_real_distribution<br>(ユニフォーム・リアル・ディストリビューション) | 実数の一様分布 |
| normal_distribution<br>(ノーマル・ディストリビューション) | 正規分布 |

2025年現在、標準ライブラリの疑似乱数に限ると`mt19937`が選択されることが多いです。しかし、データサイズが大きいなど欠点があるため、C++26では`Philox`(フィロックス)という新しい疑似乱数が導入される予定です。<br>
品質より高速性を重視する場合は`minstd_rand`を使います。

とはいえ、多くのゲームでは`PCG`や`xoroshiro`などの、標準ライブラリ以外の新しい疑似乱数プログラムを使うことが多いです。<br>
どちらも基本部分は10行程度のプログラムなので、実際に書いてみるとよいでしょう。

>「高品質な乱数」とは、以下の性質を満たすもののことです。
>* 同じパターンが生成されるまでの間隔(周期といいます)が十分に長い
>* 生成される数値にかたよりがない(例えば、32ビットで表現できる数値がまんべんなく出現する)


### 1.7 C++の言語能力を拡張するための機能

標準ライブラリには、C++に最初から組み込まれている機能だけでは実現できない、より複雑な機能を実現するためのクラスや関数が含まれます。これらの機能については、別の回に解説する予定です。


| ライブラリ名 | 概要 |
|:-------------|:-----|
| memory(メモリ) | 安全な動的メモリ管理 |
| thread(スレッド)<br>mutex(ミューテックス)<br>future(フューチャー) | マルチスレッド、並行プログラミングのサポート |
| exception(エクセプション) | 実行時エラーを補足・制御する「例外」機能のサポート |
| local(ロケール) | 多言語の情報の取得 |
| typeinfo(タイプ・インフォ) | 型の情報の取得 |


----

## 2 汎用アルゴリズムの使い方

----


### 2.1 swap(スワップ)関数

この章では、よく使われるいくつかの汎用アルゴリズムについて、実際の使用例をあげて解説します。

最初に紹介するのは`swap`(スワップ)関数です。この関数は、引数で渡された２つの変数の内容を入れ替えます。<br>
書きかたは次のようになります。

`void swap(変数1, 変数2);`

次のプログラムは、`swap`関数を使った例です。

**コード**

```cpp
#include <iostream>
#include <string>
#include <algorithm>
using namespace std;

int main() {
  int a = 1, b = 2;
  string s = "123", t = "abc";

  cout << "swap前:" << endl;
  cout << "  a=" << a << ", b=" << b << endl;
  cout << "  s=" << a << ", t=" << b << endl;

  swap(a, b);
  swap(s, t);

  cout << "swap後:" << endl;
  cout << "  a=" << a << ", b=" << b << endl;
  cout << "  s=" << a << ", t=" << b << endl;
}
```

**実行結果**

```txt
swap前:
  a=1, b=2
  s=123, t=abc
swap後:
  a=2, b=1
  s=abc, t=123
```

`swap`関数を使わない場合、例えば`int`型の変数の値を入れ替えるには、作業用の変数を使って次のようなコードを書く必要があります。

```cpp
int a = 1, b = 2; // 入れ替えたい変数
int tmp = a; // 入れ替え作業用の変数
b = a;
a = tmp;
```

対して、`swap`関数を使うと次のように書けます。<br>
作業用の変数が不要なだけでなく、`swap`という関数名によって「値を入れ替えたい」という意図が明確になっています。

```cpp
int a = 1, b = 2;
swap(a, b);
```


### 2.2 min(ミン)関数とmax(マックス)関数

`min`関数は「２つ以上の値のうち、最も小さい値」を返す関数です。`max`関数はその逆で、「２つ以上の値のうち、最も大きい値」を返す関数です。書きかたは次のようになります。

`小さい方の値 min(値１, 値２);`<br>
`大きい方の値 max(値１, 値２);`<br>

`if`文を使って、「ある変数の値が最小値未満だったら最小値に、最大値より大きければ最大値にする」という、いわゆる「範囲を制限する」プログラムはよく見かけるものです。

次の例は、入力された値を0～100の範囲に制限して出力するプログラムです。

**コード**

```cpp
#include <iostream>
using namespace std;

int main() {
  int n;
  cin >> n;

  if (n < 0) {
    n = 0;
  } else if (n > 100) {
    n = 100;
  }

  cout << n << endl;
}
```

**入力例（１）**

```txt
-1
```

**出力例（１）**

```txt
0
```

**入力例（２）**

```txt
999
```

**出力例（２）**

```txt
100
```

`min`関数と`max`関数を使うと、この範囲制限プログラムは次のように書けます。

**コード**

```cpp
#include <iostream>
#include <algorithm>
using namespace std;

int main() {
  int n;
  cin >> n;

  n = max(n, 0);   // nと0のうち大きいほうを返す
  n = min(n, 100); // nと100のうち小さいほうを返す

  cout << n << endl;
}
```

`min`関数と `max`関数は、このような範囲制限をしたい場合によく使われます。

３つ以上のデータの最小値、または最大値を求めるには、次のようにデータを`{}`で囲みます。

**コード**

```cpp
#include <iostream>
#include <algorithm>
using namespace std;

int main() {
  cout << max( { 1, 2, 3, 4, 5 } ) << endl;
  cout << min( { 1, 2, 3, 4, 5 } ) << endl;;
}
```

**実行結果**

```txt
5
1
```

>この例の`{}`の使い方について、詳しく知りたい場合は`initializer_list`(イニシャライザ・リスト)で検索してみてください。

また、コンテナから最小、最大を求めるには、`ranges`(レンジズ)ライブラリの`min`、`max`関数を使って次のように書きます。

**コード**

```cpp
#include <iostream>
#include <vector>
#include <algorithm>
using namespace std;

int main() {
  vector<int> v = { 1, 2, 3, 4, 5 };
  cout << ranges::max(v) << endl;
  cout << ranges::min(v) << endl;;
}
```

**実行結果**

```txt
5
1
```




### 2.3 copy(コピー)関数とcopy_backward(コピー・バックワード)関数

`copy`関数は、複数のデータを先頭から終端に向かって順番にコピーします。書きかたは次のとおりです。

`コピー終了位置 copy(コピーする範囲の先頭, コピーする範囲の終端, コピー先の先頭);`

「範囲の先頭」、「範囲の終端」、「コピー先の先頭」には「イテレータ」を指定します。ただし、「範囲の先頭」から「範囲の終端」のあいだに「コピー先の先頭」が含まれていてはなりません。もし含まれていると、コピーが正しく行われません。

>`copy`関数に限らず、標準ライブラリに含まれる関数は、２つのイテレータによって操作範囲を指定するものが多いです。

次の例は、`copy`関数を使ったプログラムです。

**コード**

```cpp
#include <iostream>
#include <vector>
#include <algorithm>
using namespace std;

int main() {
  vector<int> a = { 1, 2, 3, 4, 5, 6, 7, 8 };

  copy(a.begin() + 2, a.end(), a.begin());

  for (int i = 0; i < (int)a.size(); i++) {
    cout << a[i] << " ";
  }
  cout << endl;
}
```

**実行結果**

```txt
3 4 5 6 7 8 7 8
```

`copy_backward`関数は、複数のデータを終端から先頭に向かって順番にコピーします。`copy`関数とはコピーの順序が違うだけです。<br>
書きかたは次のとおりです。

`コピー終了位置 copy_backward(コピーする範囲の先頭, コピーする範囲の終端, コピー先の終端);`

「範囲の先頭」、「範囲の終端」、「コピー先の先頭」には「イテレータ」を指定します。ただし、「範囲の先頭」から「範囲の終端」のあいだに「コピー先の終端」が含まれていてはなりません。もし含まれていると、コピーが正しく行われません。

次のプログラムは、`copy_backward`関数を使った例です。

**コード**

```cpp
#include <iostream>
#include <vector>
#include <algorithm>
using namespace std;

int main() {
  vector<int> a = { 1, 2, 3, 4, 5, 6, 7, 8 };

  copy_backward(a.begin(), a.end() - 2, a.end());

  for (int i = 0; i < (int)a.size(); i++) {
    cout << a[i] << " ";
  }
  cout << endl;
}
```

**実行結果**

```txt
1 2 1 2 3 4 5 6
```

コピーするとき、どちらの関数を使うかは、次のように決めるとよいでしょう。

* コピー先の先頭がコピー元の範囲にない場合 → `copy`関数を使う
* それ以外の場合 → `copy_backward`関数を使う


### 2.4 reverse(リバース)関数

`reverse`関数は、範囲内のデータの並び順を逆にします。書きかたはつぎのとおりです。

`void reverse(範囲の先頭, 範囲の終端);`

「範囲の先頭」と「範囲の終端」には「イテレータ」を指定します。

次の例は、`reverse`関数を使ったプログラムです。

**コード**

```cpp
#include <iostream>
#include <vector>
#include <algorithm>
using namespace std;

int main() {
  vector<int> v = { 1, 2, 3, 4, 5 };

  reverse(v.begin(), v.end());

  for (auto i = v.begin(); i != v.end(); i++) {
    cout << *i << ' ';
  }
  cout << endl;
}
```

**実行結果**

```txt
5 4 3 2 1
```

また、`ranges`ライブラリを使うともう少し簡単になり、次のように書けます。

**コード**

```cpp
#include <iostream>
#include <vector>
#include <algorithm>
using namespace std;

int main() {
  vector<int> v = { 1, 2, 3, 4, 5 };

  ranges::reverse(v);

  for (auto i = v.begin(); i != v.end(); i++) {
    cout << *i << ' ';
  }
  cout << endl;
}
```

**実行結果**

```txt
5 4 3 2 1
```

コンテナ全体を反転させたい場合は`ranges::reverse`を使い、コンテナの一部分(例えば最初の5つの要素)だけを反転させたい場合は通常の`reverse`を使うとよいでしょう。


### 2.5 sort(ソート)関数

`sort`関数は、範囲内のデータを昇順、つまり小さい順に並べ替えます。

`sort`関数の書き方は２つあります。それぞれ次のように書きます。

`sort(範囲の先頭, 範囲の終端);`<br>
`sort(範囲の先頭, 範囲の終端, 比較関数);`

最初の書きかたから見ていきましょう。このバージョンの`sort`関数は、次のように使います。

**コード**

```cpp
#include <iostream>
#include <vector>
#include <algorithm>
using namespace std;

int main() {
  vector<int> v = { 1, 7, 3, 2, 0, 5, 0, 8 };

  sort(v.begin(), v.end());

  for (auto i = v.begin(); i != v.end(); i++) {
    cout << *i << ' ';
  }
  cout << endl;
}
```

**実行結果**

```txt
0 0 1 2 3 5 7 8
```

昇順ではなく、降順に並べ替えたい場合は2つめのバージョンを使います。これは、次のようなプログラムになります。

**コード**

```cpp
#include <iostream>
#include <vector>
#include <algorithm>
using namespace std;

int main() {
  vector<int> v = { 1, 7, 3, 2, 0, 5, 0, 8 };

  sort(v.begin(), v.end(), [](int a, int b) { return a > b; });

  for (auto i = v.begin(); i != v.end(); i++) {
    cout << *i << ' ';
  }
  cout << endl;
}
```

**実行結果**

```txt
8 7 5 3 2 1 0 0
```

このプログラムでは次の無名関数を使用しています。

`[](int a, int b) { return a > b; }`

この関数の内容は、「前にある数値のほうが大きい場合に`true`、そうでなければ`false`を返す」というものです。

ピンときたかもしれませんが、次のような無名関数を与えると、最初のバージョンの`sort`と同じ動作になります。

```cpp
sort(v.begin(), v.end(), [](int a, int b) { return a < b; });
```

>**【stable_sort(ステーブル・ソート)関数について】**<br>
>`sort`関数の欠点は、「等しいと判定されたデータ同士の順序が毎回異なる」点です。もし、「等しいと判定されたデータ同士は並べ替え前の順番どおりになってほしい」場合は、代わりに`stable_sort`という関数を使います。
>
>例えば、名前と得点を持つ構造体があり、得点の小さい順に並べ替えたい場合を考えます。鈴木さんと佐藤さんの得点が同じ場合に、データが登録順になってほしいなら`stable_sort`を使い、順番がどうなってもよいなら`sort`を使います。


### 2.6 find_if(ファインド・イフ)関数

`find_if`関数の機能は、「範囲内から、条件を満たす値を見つける」というものです。

`find_if`関数は次のように書きます。

`見つけた位置 find_if(範囲の先頭, 範囲の終端, 条件);`

汎用アルゴリズムの項で説明したように、「条件」には「関数」を指定します。
`find_if`関数がやることは、次のとおりです。

1. 範囲の「先頭」から順番に「条件を満たす値」を探す
2. 値を見つけたら、「最初に見つけた位置を示すイテレータ」を返す
3. 値を見つけられないまま「終端」まで来てしまったら、「終端」の位置を返す

`find_if`を使った例を次に示します。

**コード**

```cpp
#include <iostream>
#include <vector>
#include <algorithm>
using namespace std;

int main() {
  vector<int> v = { 3, 1, 4, 1, 5, 9, 2, 6 };

  auto i = find_if(v.begin(), v.end(), [](int n) { return n > 5; });

  cout << "5より大きい最初の数は" << *i << endl;
  cout << "位置は" << distance(v.begin(), i) << "番目" << endl;
}
```

**実行結果**

```txt
5より大きい最初の数は9
位置は5番目
```

なお、上記のプログラム中で使っている`distance`(ディスタンス)関数は、第1引数のイテレータから、第2引数のイテレータまでの距離を返す関数です。


### 2.7 remove_if(リムーブ・イフ)関数

`remove_if`関数の目的は「特定のデータの削除」ですが、実は次のように少し変わった動作をします。

1. 範囲内のデータを先頭から調べ、条件を「満たさない」データだけを前側に集める
2. 条件を満たすデータは、満たさないデータより後ろ側に残される
3. すべてのデータを調べ終わったら、条件を満たすデータの先頭の位置を返す

つまり、`remove_if`関数は「実際にはデータを削除しない」のです。データの削除にはコンテナ自体が必要ですが、汎用アルゴリズムが受け取るのはイテレータなので、削除できないのです。イテレータにできるのは「要素を移動させる」ことだけです。

そこで`remove_if`関数は、削除したくない、つまり条件を「満たさない」データを範囲の前側に移動させます。全て移動させると、後ろ側には削除したいデータだけが残ります。あとは、削除したいデータの位置を返して、実際の削除はプログラマに任せます。

データを削除するには、コンテナの`erase`関数を使います。

説明だけだと分かりにくいので、配列から偶数を削除する場合の`remove_if`関数の動作例を、以下に示します。

1. 最初の位置を調べる。8は偶数なので削除対象。上書き可能な場所としてマークする。
   ```txt
                     x(上書き可能マーク)
   [8 3 2 2 1 5] -> [8 3 2 2 1 5]
    ^(調べる位置)    ^
   ```
2. 次の位置を調べる。3は奇数なので残す。上書き可能な場所があるのでコピーし、元に位置を上書き可能とマークする。
   ```txt
    x                                   x
   [8 3 2 2 1 5] -> [3 3 2 2 1 5] -> [3 3 2 2 1 5]
      ^                ^                ^
   ```
3. 次の位置を調べる。2は偶数なので削除対象。上書き可能とマークする。
   ```txt
      x                x x
   [3 3 2 2 1 5] -> [3 3 2 2 1 5]
        ^                ^
   ```
4. 次の位置を調べる。2は偶数なので削除対象。上書き可能とマークする。
   ```txt
      x x              x x x
   [3 3 2 2 1 5] -> [3 3 2 2 1 5]
          ^                ^
   ```
5. 次の位置を調べる。1は奇数なので残す。上書き可能な場所にコピーし、元の位置を上書き可能とマークする。
   ```txt
      x x x              x x              x x x
   [3 3 2 2 1 5] -> [3 1 2 2 1 5] -> [3 1 2 2 1 5]
            ^                ^                ^
   ```
6. 次の位置を調べる。5は奇数なので残す。上書き可能な場所にコピーし、元の位置を上書き可能としてマークする。
   ```txt
        x x x              x x              x x x
   [3 1 2 2 1 5] -> [3 1 5 2 1 5] -> [3 1 5 2 1 5]
              ^                ^                ^
   ```
7. 最後まで調べ終わったので、上書き可能としてマークされた最初の位置を返す。
   ```txt
          x x x
   [3 1 5 2 1 5]
          ^(この位置を戻り値にする)
   ```

続いて、実際のプログラムを見てみましょう。次のプログラムは、配列から偶数の要素を削除します。

**コード**

```cpp
#include <iostream>
#include <vector>
#include <algorithm>
using namespace std;

int main() {
  vector<int> v = { 1, 4, 1, 4, 2, 1, 3, 5, 6 };

  // 奇数の要素を前側に集める
  // 戻り値iには、削除するべきデータの先頭位置が代入される
  auto i = remove_if(v.begin(), v.end(), [](int n) { return n % 2 == 0; });

  // 位置iから最後のデータまでを削除
  v.erase(i, v.end());

  // 残ったデータを出力
  for (auto j = v.begin(); j != v.end(); j++) {
    cout << *j << ' ';
  }
  cout << endl;
}
```

**実行結果**

```txt
1 1 1 3 5
```

上の例は動作を分かりやすくするために`remove_if`と`erase`を別々の行に分けましたが、通常は次のようにまとめて書くことが多いです。

**コード**

```cpp
#include <iostream>
#include <vector>
#include <algorithm>
using namespace std;

int main() {
  vector<int> v = { 1, 4, 1, 4, 2, 1, 3, 5, 6 };

  v.erase(
    remove_if(v.begin(), v.end(), [](int n) { return n % 2 == 0; }),
    v.end());

  for (auto j = v.begin(); j != v.end(); j++) {
    cout << *j << ' ';
  }
  cout << endl;
}
```

このような、汎用アルゴリズムの`remove_if`関数と、コンテナの`erase`関数を組み合わせて使うことは、データを削除する定番の書きかた(イディオム)です。C++プログラマのあいだでは、この書きかたには「`erase-remove`(イレース・リムーブ)イディオム」という名前がついています。


### 2.8 unique(ユニーク)関数

`unique`関数の機能は、「範囲から重複するデータをなくして、唯一の(つまり、ユニークな)データだけにする」ことです。ですが、`remove_if`関数でも解説したように、汎用アルゴリズムはコンテナの要素を削除できません。

そのため、`unique`関数が実際に行うのは、`remove_if`と同様の「削除しないデータを範囲の前方に集める」という処理です。

1. 範囲内のデータを先頭から調べ、「隣り合う等しいデータ」を見つけたら、先頭のデータだけを前側に集める
2. 残りのデータは後ろ側に残される
3. すべてのデータを調べ終わったら、集めなかったデータの先頭の位置を返す

実際のデータの削除には、コンテナの`erase`関数を使います。

また、重複していると判定できるのは「隣り合う等しいデータ」に限られます。例えば、次のようなデータがあるとします。

`1 1 7 1 1 1 3 3`

このデータ全体に対して`erase`と`unique`を実行すると、次の結果になります。

`1 7 1 3`

この例では、最初の2つの`1`と、`7`の次から始まる3つの`1`は、途中の`7`で分断されて2つのグループになっています。<br>
そのため、グループごとにユニークなデータが残されて、`1`が2つ残ってしまうのです。

名前のとおりに「ユニークなデータ」だけを残すには、事前に等しいデータが全て隣接するように並べ替えておく必要があります。<br>
この並べ替えは、`sort`関数を使えば簡単にできます。

`sort`関数を使って前のデータを並べ替えると、次のようになります。

`1 1 1 1 1 3 3 7`

この状態にしてから`erase`と`unique`を実行すれば、次のように「ユニークなデータだけ」の結果が得られます。

`1 3 7`

次の例は、`unique`、`erase`、`sort`を組み合わせて重複をなくすプログラムです。

**コード**

```cpp
#include <iostream>
#include <vector>
#include <algorithm>
using namespace std;

int main() {
  vector<int> v = { 2, 7, 1, 8, 2, 8, 1, 8, 2, 8, 4, 5, 9, 0, 4 };

  sort(v.begin(), v.end());
  v.erase(unique(v.begin(), v.end()), v.end());

  for (auto j = v.begin(); j != v.end(); j++) {
    cout << *j << ' ';
  }
  cout << endl;
}
```

**実行結果**

```txt
0 1 2 4 5 7 8 9
```


----

## 3 練習問題

----

以下の手順にしたがって、各問題のプログラムを完成させなさい。

1. `%%writefile ...`の下の行からがプログラムです。問題文に従ってプログラムを修正、または追加してください。
2. プログラムを修正したら、セルの右側にある`▶`をクリックします。すると、ファイルが保存されます。
3. 「動作テスト」セルの`▶`をクリックすると、2で保存したファイルがコンパイル＆実行され、実行結果が表示されます。<br>
   このセルは、修正したプログラムの動作を確認するために使ってください。
4. 「実行」セルの`▶`をクリックすると、2で保存したファイルがコンパイル＆実行され、結果の成否が判定されます。
5. 判定に成功したら`AC`と表示されます。次の問題に進んでください。
6. 失敗したら`WA`と表示されます(その前にエラーメッセージが表示される場合もあります)。<br>
   これは、プログラムのどこかにエラーがあることを意味します。<br>
   「動作テスト」を使ってエラーを修正し、`AC`を目指してください。


### ❓️問題１

1個の文字列が入力されます。<br>
入力された文字列が`dog`のときは`ワンワン`、`cat`のときは`ニャーニャー`、それ以外のときは`ガオー`と出力するプログラムを作成しなさい。

| 入力 | 出力する文字列 |
|:----:|:---------------|
| <font size=2>dog</font> | ワンワン     |
| <font size=2>cat</font> | ニャーニャー |
| その他                  | ガオー       |

<br><details><summary>🗝️(クリックでヒントを見る)</summary>

**プログラム例**

1. `string`型の変数`s`を定義する
2. if文を使って、`s`が文字列`dog`と等しい場合は、標準出力`cout`に文字列`ワンワン`を出力する
3. else if文を使って、`s`が文字列`cat`と等しい場合は、標準出力`cout`に文字列`ニャーニャー`を出力する
4. else句を使って、標準出力`cout`に文字列`ガオー`を出力する

</details><br>

**入力データ例（１）**

```
dog
```

**出力例（１）**

```txt
ワンワン
```

**入力データ例（２）**

```
cat
```

**出力例（２）**

```txt
ニャーニャー
```

**入力データ例（３）**

```
doggie
```

**出力例（３）**

```txt
ガオー
```


In [ ]:
%%writefile practice_01a.cpp
#include <iostream>
#include <string>
using namespace std;

int main() {
  // この下に、文字列を読み込んで鳴き声を出力するプログラムを書く

}

In [ ]:
# @title 動作テスト
!g++ -std=c++20 -O2 -Wall -Wextra -o practice_01a practice_01a.cpp && echo "この下をクリックして、動物の名前を入力" && ./practice_01a

In [ ]:
# @title 実行
!diff -Z <(echo -e "ワンワン\nニャーニャー\nガオー") <(g++ -std=c++20 -O2 -Wall -Wextra -o practice_01a practice_01a.cpp && echo "dog" | ./practice_01a && echo "cat" | ./practice_01a && echo "human" | ./practice_01a) > nil && test $? -eq 0 && echo -e "\033[32;1mAC" || echo -e "\033[31;1mWA"

In [ ]:
# @title 🔒解答例(どうしても問題を解けない場合に見てください)
%%writefile practice_01a.cpp
#include <iostream>
#include <string>
using namespace std;

int main() {
  // この下に、文字列を読み込んで鳴き声を出力するプログラムを書く
  string s;
  cin >> s;

  if (s == "dog") {
    cout << "ワンワン" << endl;
  } else if (s == "cat") {
    cout << "ニャーニャー" << endl;
  } else {
    cout << "ガオー" << endl;
  }
}